apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: build-definitions-slack-webhook-notification-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        key: "production/integration-service/tekton-ci/build-definitions-slack-webhook-notification-secret"
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: build-definitions-slack-webhook-notification-secret
