---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: application-service
  namespace: application-service
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: namespaces
  - group: ""
    resource: configmaps
  - group: appstudio.redhat.com
    identityHash: f1fbaad22d3651647c4c0b6aed3dcc58202b5171518bbfa83938ca0883595e9d
    resource: applications
  - group: appstudio.redhat.com
    identityHash: f1fbaad22d3651647c4c0b6aed3dcc58202b5171518bbfa83938ca0883595e9d
    resource: applicationsnapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: f1fbaad22d3651647c4c0b6aed3dcc58202b5171518bbfa83938ca0883595e9d
    resource: components
  - group: appstudio.redhat.com
    identityHash: f1fbaad22d3651647c4c0b6aed3dcc58202b5171518bbfa83938ca0883595e9d
    resource: componentdetectionqueries
  - group: appstudio.redhat.com
    identityHash: f1fbaad22d3651647c4c0b6aed3dcc58202b5171518bbfa83938ca0883595e9d
    resource: environments
  - group: appstudio.redhat.com
    identityHash: spi
    resource: spiaccesstokens
  - group: appstudio.redhat.com
    identityHash: spi
    resource: spiaccesstokenbindings
